### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by prologic** [dannypsnl/elz#166]
I haven't looked into this too much yet but the buidl fails on master right now:

```
$ make install
installing elz compiler...
elz compiler installed
installing elz libs...
installing lib: list...
lib: list installed
installing lib: memory...
lib: memory installed
string.c:61:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
  printf(cstr);
         ^~~~
string.c:61:10: note: treat the string as an argument to avoid this
  printf(cstr);
         ^
         "%s",
string.c:63:3: error: use of undeclared identifier 'delete'
  delete[] cstr;
  ^
string.c:63:10: error: expected expression
  delete[] cstr;
         ^
1 warning and 2 errors generated.
make[2]: *** [string.o] Error 1
make[1]: *** [all] Error 2
make: *** [install] Error 2

```

**Comment by prologic** [comment]
This is on macOS with Homebrew and Go 1.12.1

**Comment by dannypsnl** [comment]
Make sense for me, I'm working on [type inferencing](https://github.com/elz-lang/elz/blob/master/compiler/src/semantic/mod.rs) right now and lib string do not be used by compiler actually, I think you can just remove it.

The Go implementation now has totally wrong & poor semantic checking was lead by my lack of knowledge, and since everything should change so the main code is at https://github.com/elz-lang/elz/blob/master/compiler which using Rust. Hope you haven't jumped into it yet :).

And I think the plan would be using front-end(Rust part) to generate some MIR which already has detected machine level type & using https://github.com/llir/llvm to generate LLVM IR.

**Comment by prologic** [comment]
I see. Which part specifically do you mean we can remove?

So you're re-writing the compiler frontend in Rust now? Why? :)

**Comment by dannypsnl** [comment]
`core/string` this directory can be removed for now.

The major reason that using Rust:
- union tagged type, restrict some type as the same type no need to define some weird interface, I found Go `ast.Type` accidentally satisfied `types.Type` at branch `r-161` which is annoying
    ```
    enum Type {
        I64,
        F64,
        TypeVar(TypeVar),
    }
    ```
- `Result` type can omit no need error handling, for example, https://github.com/elz-lang/elz/blob/3541e4701b3e779f9bd173ea7d21a8bfbc0fe732/src/elz/parser/parser.go#L175 at here we can do nothing for the error because we would recover parsing state later and report mismatching error, and such code is everywhere is Go version.

**Comment by prologic** [comment]
Where's the old Go reference code now? Is it still kept somewhere in a branch?

**Comment by prologic** [comment]
I'e like to have access to the Go code in some working state if I can :)

**Comment by dannypsnl** [comment]
> Where's the old Go reference code now? Is it still kept somewhere in a branch?

https://github.com/elz-lang/elz/tree/code-gen-ref I put it into the branch(code-gen-ref) first.

I think you can start at #167 this issue, would need a MIR format for code generation. Then can add a generator for MIR.

**Comment by prologic** [comment]
That branch now has Rust code. Do you know which specific commit sha/hash still has the old Go code? Do you mind if I fork from that point? I'm interested in learning about LLVM and wanted to do so with your original Go implemtnation of elz.

**Comment by dannypsnl** [comment]
> Do you know which specific commit sha/hash still has the old Go code?
https://github.com/elz-lang/elz/commit/5ad7c11350da2306a451d761bd1edb7c5e786219
> Do you mind if I fork from that point?
It fine.

I think you can first start from this: https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/

**Comment by prologic** [comment]
Thanks; but I really wanted access to your old Go code :)

**Comment by dannypsnl** [comment]
I didn't get it, the code is under `src/elz/codegen`, and you can access it as you wish.

**Comment by prologic** [comment]
Thanks I found it finally :)

**Comment by dannypsnl** [comment]
Ok, now I got it, the code structure is clear for me, but hard to be found by others 😂

And I would say the type check in `codegen` is wrong, that should be done before generating IR because if we did check at that time, we would skip the code those unused; and there are some duplicates between `types` and `codegen`.
