### ISSUE TITLE
report more error at once

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#267]
The reason is simple, show errors as much as users can fix at once to improve the developing cycle.

- [ ] once report any parse error, don't report semantic error(probably don't need code changes)
- [ ] each file report at most one parse error
- [ ] each function/trait/class/variable at most one semantic error

**Comment by dannypsnl** [comment]
and also should improve the report content:

![image](https://user-images.githubusercontent.com/22004511/75602040-6d494c00-5afc-11ea-86f6-0cac46128e80.png)

error point to `1` would be better.

**Comment by dannypsnl** [comment]
A possible approach is collecting errors on each top-level AST. report one error for each top-level AST

**Comment by YanHerChen** [comment]
Compile will call semantic_checker to check semantic. SemanticChecker's check_program function has four loops, the last one is to check the module.
We hope to remove the error result currently returned by semantic, and add the context record error information in order to obtain more error information.
After the check_program is executed, the context will determine whether there is an error to be returned.

**Comment by dannypsnl** [comment]
Good to see you start working on this!

**Comment by dannypsnl** [comment]
> https://github.com/dannypsnl/elz/issues/267#issuecomment-633226477

@YanHerChen I think there has another solution. Directly report at the point where the error occurs, then only a `bool` is required for stop code generation. It depends on you.
